// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-QsfKasMJXXxxpO7tX64QIHLN_wYirVA',
    appId: '1:165651709588:web:d9eb45279d8e244f673e81',
    messagingSenderId: '165651709588',
    projectId: 'grad-project-bf552',
    authDomain: 'grad-project-bf552.firebaseapp.com',
    storageBucket: 'grad-project-bf552.appspot.com',
    measurementId: 'G-1P46MEXX1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeWfES6fBXLUg1yqHS7L6CV292414FOVY',
    appId: '1:165651709588:android:16cbca0ab8edc25c673e81',
    messagingSenderId: '165651709588',
    projectId: 'grad-project-bf552',
    storageBucket: 'grad-project-bf552.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQK8Ogsr9tGtUtuYZpfNvg-euKddYMYgs',
    appId: '1:165651709588:ios:9c25c89d0593e28e673e81',
    messagingSenderId: '165651709588',
    projectId: 'grad-project-bf552',
    storageBucket: 'grad-project-bf552.appspot.com',
    androidClientId: '165651709588-9uk0bado6a98jopoebe8k4m69jjgcoeo.apps.googleusercontent.com',
    iosClientId: '165651709588-58ge578hsndlim7e03s4uvrs4porac2r.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQK8Ogsr9tGtUtuYZpfNvg-euKddYMYgs',
    appId: '1:165651709588:ios:48f7d6e75fde7a90673e81',
    messagingSenderId: '165651709588',
    projectId: 'grad-project-bf552',
    storageBucket: 'grad-project-bf552.appspot.com',
    androidClientId: '165651709588-9uk0bado6a98jopoebe8k4m69jjgcoeo.apps.googleusercontent.com',
    iosClientId: '165651709588-n6lbqt5u0ufsr4rje1f8b38tdmiasjr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradProj.RunnerTests',
  );
}
